# Indra Service Sample Runtime Configuration


httpBasePath: /indra/v1
mongoURI: mongodb://localhost:27017

models:
    - LSA
    - ESA
    - GLOVE
    - W2V
    - DEP

languages:
    - EN
    - DE
    - PT

security:
  enabled: yes
  user: indra
  pass: ki87nnbg53R
